import {firebaseConfig} from "./firebase-config.js";import{initializeApp}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";import{getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";import{getFirestore,collection,doc,setDoc,updateDoc,onSnapshot,query,orderBy}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id),states=["Recibido","En diagnóstico","Esperando autorización","En reparación","Esperando refacción","En pruebas","Terminado","Entregado"];let all=[];
$("loginBtn").onclick=async()=>{try{await signInWithEmailAndPassword(auth,$("email").value,$("pass").value)}catch(e){$("loginMsg").textContent="Acceso no autorizado"}};$("logout").onclick=()=>signOut(auth);
onAuthStateChanged(auth,u=>{$("login").classList.toggle("hidden",!!u);$("dashboard").classList.toggle("hidden",!u);if(u)listen()});
$("crear").onclick=async()=>{let now=Date.now(),folio=`XE-${new Date().getFullYear()}-${String(now).slice(-6)}`,d={cliente:$("cliente").value,telefono:$("telefono").value,equipo:$("equipo").value,modelo:$("modelo").value,falla:$("falla").value,nota:$("nota").value,estado:"Recibido",recibido:now,actualizado:now,entregado:null};if(!d.cliente||!d.equipo)return alert("Escribe cliente y equipo");await setDoc(doc(db,"equipos",folio),d);
let pub={equipo:d.equipo,modelo:d.modelo,nota:d.nota,estado:d.estado,recibido:d.recibido,actualizado:d.actualizado,entregado:d.entregado};
await setDoc(doc(db,"estados_publicos",folio),pub);$("created").textContent=`FOLIO CREADO: ${folio}`;["cliente","telefono","equipo","modelo","falla","nota"].forEach(x=>$(x).value="")};
function listen(){onSnapshot(query(collection(db,"equipos"),orderBy("recibido","desc")),s=>{all=s.docs.map(x=>({id:x.id,...x.data()}));render()})}$("filter").oninput=render;
function render(){let f=$("filter").value.toLowerCase(),arr=all.filter(x=>(x.id+" "+x.cliente+" "+x.equipo).toLowerCase().includes(f));$("list").innerHTML=arr.map(x=>`<div class="item"><div class="itemtop"><div><h3>${x.id} · ${esc(x.equipo)}</h3><p>${esc(x.cliente)} · ${esc(x.falla||"Sin falla reportada")}</p></div><b>${x.estado}</b></div><div class="controls"><select data-state="${x.id}">${states.map(s=>`<option ${s===x.estado?"selected":""}>${s}</option>`).join("")}</select><textarea data-note="${x.id}">${esc(x.nota||"")}</textarea><button data-save="${x.id}">GUARDAR</button></div></div>`).join("");document.querySelectorAll("[data-save]").forEach(b=>b.onclick=async()=>{let id=b.dataset.save,estado=document.querySelector(`[data-state="${id}"]`).value,nota=document.querySelector(`[data-note="${id}"]`).value,upd={estado,nota,actualizado:Date.now()};if(estado==="Entregado"){let old=all.find(x=>x.id===id);upd.entregado=old.entregado||Date.now()}await updateDoc(doc(db,"equipos",id),upd);await updateDoc(doc(db,"estados_publicos",id),upd)})}
function esc(s){return String(s).replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}