import {firebaseConfig} from "./firebase-config.js";
import{initializeApp}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import{getFirestore,doc,onSnapshot}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
const app=initializeApp(firebaseConfig),db=getFirestore(app),$=id=>document.getElementById(id);let current,unsub;
$("buscarCita").onclick=()=>watch($("folioCita").value.trim().toUpperCase());
function watch(f){if(!f)return;if(unsub)unsub();$("folioCita").value=f;unsub=onSnapshot(doc(db,"citas_publicas",f),s=>{if(!s.exists()){$("msgCita").textContent="Folio de cita no encontrado.";$("resultadoCita").classList.add("hidden");return}current={id:s.id,...s.data()};render()},()=>$("msgCita").textContent="No fue posible consultar la cita.")}
function render(){$("msgCita").textContent="";$("resultadoCita").classList.remove("hidden");$("cFolio").textContent=current.id;$("cEstado").textContent=current.estado;$("cFechaHora").textContent=`${formatearFecha(current.fecha)} · ${formatearHora(current.hora)}`;$("cCliente").textContent=current.cliente;$("cEquipo").textContent=current.equipo;$("cModelo").textContent=current.modelo||"No especificado";$("cFalla").textContent=current.falla||"No especificada";$("cHistorial").innerHTML=(current.historial||[]).slice().reverse().map(h=>`<div class="history-entry"><small>${new Date(h.fecha).toLocaleString("es-MX")}</small><b>${esc(h.tipo)}</b><span>${esc(h.detalle||"")}</span></div>`).join("")||"<p>Sin movimientos.</p>"}
$("pedirReagendar").onclick=()=>{if(!current)return;const m=`Hola, soy ${current.cliente}.\n\nFolio: ${current.id}\n\nMe gustaría solicitar reagendar mi cita.\n\nGracias.`;window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(m)}`,"_blank")};
$("solicitarLlamada").onclick=()=>{if(!current)return;const m=`Hola, soy ${current.cliente}.\n\nFolio: ${current.id}\n\nMe gustaría comunicarme con el equipo de XE Servicio Electrónico. Cuando tengan oportunidad, ¿podrían llamarme por WhatsApp?\n\nGracias.`;window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(m)}`,"_blank")};
$("descargarPdf").onclick=()=>generarPDF(current);
function generarPDF(x){if(!window.jspdf)return alert("No se pudo cargar el generador PDF.");const{jsPDF}=window.jspdf,p=new jsPDF();p.setFillColor(8,48,92);p.rect(0,0,210,42,"F");p.setTextColor(210,225,236);p.setFont("helvetica","bold");p.setFontSize(25);p.text("XE",18,27);p.setFontSize(16);p.text("CONFIRMACIÓN DE CITA",50,20);p.setFontSize(9);p.text("XE SERVICIO ELECTRÓNICO",50,28);p.setTextColor(35,45,55);p.setFontSize(11);let y=60;[["Folio",x.id],["Cliente",x.cliente],["Equipo",x.equipo],["Modelo",x.modelo||"No especificado"],["Falla reportada",x.falla||"No especificada"],["Fecha",formatearFecha(x.fecha)],["Hora",formatearHora(x.hora)],["Estado",x.estado]].forEach(([a,b])=>{p.setFont("helvetica","bold");p.text(a+":",20,y);p.setFont("helvetica","normal");const lines=p.splitTextToSize(String(b),125);p.text(lines,65,y);y+=Math.max(10,lines.length*6)});p.setDrawColor(160,175,185);p.line(20,270,190,270);p.setFont("helvetica","bold");p.setFontSize(10);p.text("XE SERVICIO ELECTRÓNICO",105,278,{align:"center"});p.setFont("helvetica","normal");p.text("Expertos en Tecnología",105,284,{align:"center"});p.save(`Cita-${x.id}.pdf`)}
function formatearFecha(v){return v?new Date(v+"T12:00:00").toLocaleDateString("es-MX",{weekday:"long",day:"numeric",month:"long",year:"numeric"}):"Sin fecha"}function formatearHora(v){if(!v)return"Sin hora";const[h,m]=v.split(":");return new Date(2000,0,1,+h,+m).toLocaleTimeString("es-MX",{hour:"numeric",minute:"2-digit"})}function esc(s){return String(s||"").replace(/[&<>\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}
const f=new URLSearchParams(location.search).get("folio");if(f)watch(f.trim().toUpperCase());
